name: Daily WOD Fetcher

on:
  schedule:
    # Run every day at 07:00 AM UTC
    - cron: '0 7 * * *'
    # Run every day at 02:00 PM UTC (14:00)
    - cron: '0 14 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_wod_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use the latest Python 3.x version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run WOD script
      env:
        # These secrets must be added to your GitHub repository settings
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        SUGARWOD_API_KEY: ${{ secrets.SUGARWOD_API_KEY }}
      run: python get_wod.py 